-- Create a table as unique value

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states(
	`id` INT UNIQUE AUTO_INCREMENT NOT NULL,
	`name` VARCHAR(256) NOT NULL
);

ALTER TABLE states ADD PRIMARY KEY (`id`);
